name: Process

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup codebase
        uses: actions/checkout@v2

      - name: "Setup Python3"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 


      - name: "Updating raport"
        run: |
          python3 render.py
          git pull https://github.com/L1ghtDream/raport
          mv README.md raport/README.md
          cd raport
          git add *
          git config --global user.email "admin@voinearadu.com"
          git config --global user.name "Radu Voinea"
          git remote set-url origin https://L1ghtDream:${{ secrets.PERSONAL_TOKEN }}@github.com/L1ghtDream/raport
          git commit -m "Updated README.md"
          git push --set-upstream origin master